#!/bin/bash
set -eux
install -D /dev/stdin ~/.docker/config.json <<EOF
{"experimental": "enabled"}
EOF

docker version

platforms=linux/amd64,linux/arm64

docker run --rm --privileged multiarch/qemu-user-static:register --reset --persistent yes
docker buildx create --use --platform "$platforms"
docker buildx build --load --platform "$platforms" -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .
