#!/bin/bash
set -eux
install -D /dev/stdin ~/.docker/config.json <<EOF
{"experimental": "enabled"}
EOF

docker version


docker buildx create --use

docker buildx ls

docker buildx build --load --platform linux/amd64,linux/arm64 -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .
