#!/bin/bash
set -eux
install -D /dev/stdin ~/.docker/config.json <<EOF
{"experimental": "enabled"}
EOF

docker version

docker buildx create --use
docker buildx build --load -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .
